server:
    port: "467"
    host: "message-service"
    secret: "MagyGram"
    name: "message-service"
    handshake: "ms-handshake"

database:
    host: "redis-db"
    port: "6379"
    password: ""
    database: 0

authservice:
    protocol: "http://"
    domain: "auth-service"
    port: "461"

userservice:
    protocol: "http://"
    domain: "user-service"
    port: "460"
