server :
  port : "467"
  host : "message-service"
  secret : "MagyGram"
  name: "message-service"
  handshake : "ms-handshake"

database :
  host : "redisdb-db"
  port : "6379"
  password : ""
  database : 0

authservice:
  protocol: "http://"
  domain: "auth-service"
  port: "461"