services:

  gateway:
    image: nginx:1.19.8-alpine
    ports:
      - 8085:443
    networks:
      - backend
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./gateway/api_gateway.conf:/etc/nginx/api_gateway.conf
      - ./gateway/certificate.pem:/etc/nginx/ssl/certificate.pem
      - ./gateway/certificate-key.pem:/etc/nginx/ssl/certificate-key.pem
  
  tracing:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
    networks:
      - backend

networks:
  backend:
    name: magygram
    driver: bridge