services:

  gateway:
    image: nginx:1.19.8-alpine
    ports:
      - 8085:443
    networks:
      - backend
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./gateway/api_gateway.conf:/etc/nginx/api_gateway.conf
      - ./gateway/certificate.pem:/etc/nginx/ssl/certificate.pem
      - ./gateway/certificate-key.pem:/etc/nginx/ssl/certificate-key.pem

networks:
  backend:
    name: magygram
    driver: bridge