server :
  port : "466"
  host : "localhost"
  secret : "MagyGram"
  name: "request-service"
  handshake : "ms-handshake"

database :
  host : "mongodb://localhost"
  port : "27017"
  user : "root"
  password : "root"
  database : "no-waiter-request-service"

mail :
  sender : "info.magygram@gmail.com"
  password : "magygramxml"
  host : "smtp.gmail.com"
  port : "587"

