server :
  port : "460"
  host : "localhost"
  secret : "MagyGram"
  name: "user-service"
  handshake : "ms-handshake"

database :
  host : "mongodb://localhost"
  port : "27017"
  user : "root"
  password : "root"
  database : "no-waiter-user-service"

mail :
  sender : "info.magygram@gmail.com"
  password : "magygramxml"
  host : "smtp.gmail.com"
  port : "587"


authservice:
  protocol: "https://"
  domain: "localhost"
  port: "461"

relationshipservice:
  protocol: "https://"
  domain: "localhost"
  port: "463"

postservice:
  protocol: "https://"
  domain: "localhost"
  port: "462"

storyservice:
  protocol: "https://"
  domain: "localhost"
  port: "464"

mediaservice:
  protocol: "https://"
  domain: "localhost"
  port: "465"

gateway:
  port: "8085"
  protocol: "https://"
  domain: "localhost"