server:
    port: "464"
    host: "story-service"
    secret: "MagyGram"
    name: "story-service"
    handshake : "ms-handshake"

database:
    host: "mongodb://mongo-db"
    port: "27017"
    user: "root"
    password: "root"
    database: "no-waiter-story-service"

mail:
    sender: "info.magygram@gmail.com"
    password: "magygramxml"
    host: "smtp.gmail.com"
    port: "587"

mediaservice:
    protocol: "http://"
    domain: "media-service"
    port: "465"

authservice:
    protocol: "http://"
    domain: "auth-service"
    port: "461"

userservice:
    protocol: "http://"
    domain: "user-service"
    port: "460"

relationshipservice:
    protocol: "http://"
    domain: "relationship-service"
    port: "463"
