server :
  port : "461"
  host : "localhost"
  secret : "MagyGram"
  name: "auth-service"
  handshake : "ms-handshake"

database :
  host : "mongodb://localhost"
  port : "27017"
  user : "root"
  password : "root"
  database : "no-waiter-auth-service"

mail :
  sender : "info.magygram@gmail.com"
  password : "magygramxml"
  host : "smtp.gmail.com"
  port : "587"

userservice:
  protocol: "https://"
  domain: "localhost"
  port: "460"

redisdatabase:
  host: "localhost"
  port: "6379"
  password: ""
  database: 0