server:
    port: "463"
    host: "relationship-service"
    secret: "MagyGram"
    name: "relationship-service"
    handshake : "ms-handshake"

database:
    host: "bolt://neo4j-db"
    port: "7687"
    user: "neo4j"
    password: "neo4jdb"
    database: "no-waiter-relationship-service"

mail:
    sender: "info.magygram@gmail.com"
    password: "magygramxml"
    host: "smtp.gmail.com"
    port: "587"

userservice:
    protocol: "http://"
    domain: "user-service"
    port: "460"

authservice:
    protocol: "http://"
    domain: "auth-service"
    port: "461"

redisdatabase:
    host: "redis-db"
    port: "6379"
    password: ""
    database: 0
