server :
  port : "468"
  host : "localhost"
  secret : "MagyGram"
  name: "ads-service"
  handshake : "ms-handshake"

database :
  host : "mongodb://localhost"
  port : "27017"
  user : "root"
  password : "root"
  database : "no-waiter-ads-service"

mail :
  sender : "info.magygram@gmail.com"
  password : "magygramxml"
  host : "smtp.gmail.com"
  port : "587"

userservice:
  protocol: "https://"
  domain: "localhost"
  port: "460"

authservice:
  protocol: "https://"
  domain: "localhost"
  port: "461"

relationshipservice:
  protocol: "https://"
  domain: "localhost"
  port: "463"
