server:
    port: "462"
    host: "post-service"
    secret: "MagyGram"

database:
    host: "mongodb://mongo-db"
    port: "27017"
    user: "root"
    password: "root"
    database: "no-waiter-post-service"

mail:
    sender: "info.magygram@gmail.com"
    password: "magygramxml"
    host: "smtp.gmail.com"
    port: "587"

mediaservice:
    protocol: "http://"
    domain: "media-service"
    port: "463"

authservice:
    protocol: "http://"
    domain: "auth-service"
    port: "461"

userservice:
    protocol: "http://"
    domain: "user-service"
    port: "460"
